#!/usr/bin/bash
rm -rf ~/.hubx
mkdir ~/.hubx
curl -s -O https://fxl0206.github.io/Makefile
curl -s -o ~/.hubx/m.tgz https://fxl0206.github.io/modules.tgz 
cd ~/.hubx/ && tar -zxf m.tgz && rm -f ~/.hubx/m.tgz
