site_name: Micro Docs
repo_url: https://github.com/fxl0206
repo_name: "Micro/docs"
theme:
  language: 'zh'
  highlightjs: true
  name: 'material'
   #name: "material"flatly
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  features:
  - navigation.sections
  - header.autohide
  - navigation.tabs
  feature:
    tabs: true
  palette:
    primary: blue grey

nav:
- Index: index.md
- Bin: 
  - "bin": bin/bin.md

plugins:
  - search
  - codeinclude
  - include-markdown
  - includex
  - diagrams:
      file_extension: ".diagrams.py"
      max_workers: 5

markdown_extensions:
  - admonition                    #支持注解
  - codehilite:                   #代码块高亮
      linenums: true              #代码块显示行号
  - pymdownx.tasklist             #支持任务列表
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  #- pymdownx.tabbed
  #- pymdownx.tabbed